### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by jerryyang0611** [mr-pennyworth/alfred-asciimath#1]
This Alfred workflow is absolutely amazing. However, recently I encountered an issue where I cannot close the render window even though I've escaped the window or even quit Alfred 4.  I'm running on Mac Catalina 10.15. 

I ended up restarting the laptop to solve the issue..... Hope this potential bug gets fixed. Other than that it's absolutely great perfect workflow.

**Comment by mr-pennyworth** [comment]
I'm glad that this workflow is useful to you @jerryyang0611!
Let me see if I can figure out what might be going wrong.

In the meanwhile, run `pkill 'AsciiMath Renderer'` in terminal next time the freeze happens. That way, you can avoid the whole hassle of having to restart your machine because of the stupid workflow!

**Comment by jerryyang0611** [comment]
Thanks so much! Will definitely try that command whenever I encountered this issue again.
